### ISSUE TITLE
关于卡顿问题

### ISSUE THREAD

**Issue by EggOxygen** [wchdsk/WinTouch-to-Multi#1]
本人替换驱动之后出现游戏卡顿 具体体现在点一下会瞬间卡0.5秒左右 然后恢复 但在正常Windows情况不会卡顿

**Comment by wchdsk** [comment]
系统和电脑的基本配置？代码都尽量简化过了，从收到触摸窗体信息到转换成红外屏的信号到传递信息大概就几ms，估计触摸设备或者是系统原因的可能性比较大。

**Comment by EggOxygen** [comment]
win10 + 7700hq 基本玩起来是没问题的。经过我自己多次测试发现如果用一根手指按住一处 比如fever 再玩就不会卡顿。系统部分我这几天再排查看看

**Comment by EggOxygen** [comment]
经过多次测试之后可以正常使用了 是Windows10的锅 现在还有一个问题就是Windows有时候会把双指辨识为右键菜单 我在系统里面也找不到解决办法 这样有解吗？

**Comment by wchdsk** [comment]
控制面板-笔和触控-触控-选中[长按]后按右下角设置，勾掉将长按用作右键菜单就行

**Comment by EggOxygen** [comment]
OK 感谢大佬
